name: Publish to Github Packages

on:
  release:
    types: [created]
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tvl-labs'
          always-auth: true

      - run: yarn
      - run: yarn build
      - run: yarn config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - run: yarn config set @tvl-labs:registry https://npm.pkg.github.com
      - run: yarn publish